#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7312395885:AAGsoT9UhR5w5UWZm4t1rB5hP1JbiMETseY")
    API_ID = int(os.environ["API_ID", 23303247]
    API_HASH = os.environ["API_HASH", "23623f737dc15708708c65a7297e1510"]
    AUTH_USERS = "6988460039"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
